command_line_exclusions:
  columns:
  - column_index: 0
    column_type: REGEX
    key_column: null
    mapped_column_path: null
    original_column: principal_command_line
  - column_index: 1
    column_type: REGEX
    key_column: null
    mapped_column_path: null
    original_column: target_command_line
  create_time: '2025-09-18T06:49:26.874973Z'
  description: null
  resource_name: projects/sumitpatel-lab-1/locations/us/instances/2ee28a72-7a79-4197-acf9-7a731a89953c/dataTables/command_line_exclusions
  row_time_to_live: null
  rule_associations_count: null
  rules: null
  update_time: '2025-09-18T06:49:26.874973Z'
  uuid: 1cb6e279b35b4b0a8b748bd99690a996
data_table_ws_subsidiary_users:
  columns:
  - column_index: 0
    column_type: null
    key_column: null
    mapped_column_path: entity.user.userid
    original_column: userid
  - column_index: 1
    column_type: null
    key_column: null
    mapped_column_path: entity.user.company_name
    original_column: organization
  - column_index: 2
    column_type: STRING
    key_column: null
    mapped_column_path: null
    original_column: state
  - column_index: 3
    column_type: STRING
    key_column: null
    mapped_column_path: null
    original_column: probationary
  - column_index: 4
    column_type: null
    key_column: null
    mapped_column_path: entity.user.hire_date.seconds
    original_column: start_date
  create_time: '2025-09-18T06:49:30.463774Z'
  description: null
  resource_name: projects/sumitpatel-lab-1/locations/us/instances/2ee28a72-7a79-4197-acf9-7a731a89953c/dataTables/data_table_ws_subsidiary_users
  row_time_to_live: null
  rule_associations_count: null
  rules: null
  update_time: '2025-09-18T06:49:30.463774Z'
  uuid: a360fbcfbeaf47a89493c3b055c9d586
newtable:
  columns:
  - column_index: 0
    column_type: STRING
    key_column: null
    mapped_column_path: null
    original_column: a
  - column_index: 1
    column_type: STRING
    key_column: null
    mapped_column_path: null
    original_column: b
  create_time: '2025-09-18T06:49:31.526765Z'
  description: null
  resource_name: projects/sumitpatel-lab-1/locations/us/instances/2ee28a72-7a79-4197-acf9-7a731a89953c/dataTables/newtable
  row_time_to_live: null
  rule_associations_count: null
  rules: null
  update_time: '2025-09-18T06:49:31.526765Z'
  uuid: 40714b4bd65347f2aee465cb7eb3d853
